var _get_waiting_games_query_handler_test_8cs =
[
    [ "Connect4.Domain.Queries.UnitTests.GetWaitingGamesQueryHandlerTest", "class_connect4_1_1_domain_1_1_queries_1_1_unit_tests_1_1_get_waiting_games_query_handler_test.html", "class_connect4_1_1_domain_1_1_queries_1_1_unit_tests_1_1_get_waiting_games_query_handler_test" ]
];