var _not_your_turn_domain_exception_test_8cs =
[
    [ "Connect4.Domain.Exceptions.UnitTests.NotYourTurnDomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_not_your_turn_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_not_your_turn_domain_exception_test" ]
];