var _unauthorized_domain_exception_test_8cs =
[
    [ "Connect4.Domain.Exceptions.UnitTests.UnauthorizedDomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_unauthorized_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_unauthorized_domain_exception_test" ]
];