var namespace_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests =
[
    [ "BusyUserDomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_busy_user_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_busy_user_domain_exception_test" ],
    [ "DomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_domain_exception_test" ],
    [ "GameNotFoundExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_game_not_found_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_game_not_found_exception_test" ],
    [ "NotYourTurnDomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_not_your_turn_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_not_your_turn_domain_exception_test" ],
    [ "UnauthorizedDomainExceptionTest", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_unauthorized_domain_exception_test.html", "class_connect4_1_1_domain_1_1_exceptions_1_1_unit_tests_1_1_unauthorized_domain_exception_test" ]
];