var namespace_connect4_1_1_domain_1_1_tests_1_1_games_list =
[
    [ "FinishedGamesStepDefinitions", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_finished_games_step_definitions.html", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_finished_games_step_definitions" ],
    [ "FinishedGamesTests", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_finished_games_tests.html", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_finished_games_tests" ],
    [ "GetWaitingGamesStepDefinitions", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_get_waiting_games_step_definitions.html", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_get_waiting_games_step_definitions" ],
    [ "GetWaitingGamesTests", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_get_waiting_games_tests.html", "class_connect4_1_1_domain_1_1_tests_1_1_games_list_1_1_get_waiting_games_tests" ]
];