var namespace_connect4_1_1_infrastructure_1_1_repositories =
[
    [ "BoardQueryRepositorySqlite", "class_connect4_1_1_infrastructure_1_1_repositories_1_1_board_query_repository_sqlite.html", "class_connect4_1_1_infrastructure_1_1_repositories_1_1_board_query_repository_sqlite" ],
    [ "UserQueryRepositorySqlite", "class_connect4_1_1_infrastructure_1_1_repositories_1_1_user_query_repository_sqlite.html", "class_connect4_1_1_infrastructure_1_1_repositories_1_1_user_query_repository_sqlite" ]
];